### ISSUE TITLE
onSingleTap example

### ISSUE THREAD

**Issue by andosubakti** [minwork/use-double-tap#19]
hi,

can you give example when using additional options onSingleTap?

thank you!

**Comment by minwork** [comment]
Hey, it can be useful if you want to detect both actions: single tap and double tap. For example you may have a list element and want to handle two actions: on single tap element is expanded or collapsed while on double tap you go to the full screen view where you can edit that list entry.

**Comment by minwork** [comment]
Closing the issue. If you need any more examples or explanation feel free to comment and reopen it.
